
import json, os

OUT = r'c:\Users\alanj\OneDrive\Desktop\ML_hvac_model\HVAC_ML_Forecasting_Eagle_Education_Paul.ipynb'

def md(*lines):
    return {'cell_type':'markdown','metadata':{},'source':list(lines)}

def code(*lines):
    return {'cell_type':'code','execution_count':None,'metadata':{},'outputs':[],'source':list(lines)}

cells = [

# ─── TITLE ────────────────────────────────────────────────────────────────────
md(
"# HVAC Electricity Forecasting - Eagle Education Paul\n",
"\n",
"**Goal:** Train a Random Forest ML model to forecast hourly electricity demand for `Eagle_education_Paul`\n",
"(Education Classroom, 4,008 m2, Eagle site), then use predictions to regulate HVAC setpoints.\n",
"\n",
"**Hardware:** ESP32 + DHT22 (temp/humidity), BMP280 (pressure), MQ-135 (CO2/air quality),\n",
"PIR HC-SR501 (occupancy), Relay Module (HVAC control).\n",
"\n",
"| Item | Detail |\n",
"|---|---|\n",
"| Building | Eagle_education_Paul |\n",
"| Usage | Education - Classroom |\n",
"| Area | 4,008 m2 / 43,143 ft2 |\n",
"| Dataset rows | 17,365 hourly readings |\n",
"| Target variable | electricity (kWh) |\n",
"| Model | Random Forest (Baseline + Tuned) |\n",
),

# ─── SECTION 0: IMPORTS ───────────────────────────────────────────────────────
md("## 0. Install & Import Libraries\n"),
code(
"import subprocess, sys\n",
"for p in ['pandas','numpy','matplotlib','seaborn','scikit-learn','joblib','scipy']:\n",
"    subprocess.check_call([sys.executable,'-m','pip','install',p,'-q'])\n",
"\n",
"import warnings; warnings.filterwarnings('ignore')\n",
"import os, json\n",
"import pandas as pd\n",
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"import matplotlib.gridspec as gridspec\n",
"import seaborn as sns\n",
"import joblib\n",
"from scipy.stats import randint\n",
"from sklearn.ensemble import RandomForestRegressor\n",
"from sklearn.model_selection import RandomizedSearchCV\n",
"from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n",
"\n",
"plt.rcParams.update({\n",
"    'figure.facecolor':'#0d1117','axes.facecolor':'#161b22',\n",
"    'axes.edgecolor':'#30363d','axes.labelcolor':'#c9d1d9',\n",
"    'xtick.color':'#c9d1d9','ytick.color':'#c9d1d9','text.color':'#c9d1d9',\n",
"    'grid.color':'#21262d','grid.linestyle':'--',\n",
"    'legend.facecolor':'#161b22','legend.edgecolor':'#30363d',\n",
"    'figure.titlesize':14,'axes.titlesize':12,'axes.labelsize':10,\n",
"})\n",
"ACCENT, ACCENT2, WARN = '#58a6ff', '#3fb950', '#f78166'\n",
"\n",
"import sklearn\n",
"print('Libraries loaded successfully')\n",
"print(f'  pandas   {pd.__version__}')\n",
"print(f'  numpy    {np.__version__}')\n",
"print(f'  sklearn  {sklearn.__version__}')\n",
),

# ─── SECTION 1: LOAD DATA ─────────────────────────────────────────────────────
md("## 1. Load Datasets\n"),
code(
"DATA_DIR   = os.getcwd()\n",
"metadata   = pd.read_csv(os.path.join(DATA_DIR, 'metadata.csv'))\n",
"ml_dataset = pd.read_csv(os.path.join(DATA_DIR, 'ml_dataset.csv'), parse_dates=['timestamp'])\n",
"\n",
"print('='*55)\n",
"print('DATASET OVERVIEW')\n",
"print('='*55)\n",
"print(f'  metadata   : {metadata.shape[0]:,} buildings x {metadata.shape[1]} attributes')\n",
"print(f'  ml_dataset : {ml_dataset.shape[0]:,} hourly rows x {ml_dataset.shape[1]} features')\n",
"print()\n",
"\n",
"TARGET_BUILDING = 'Eagle_education_Paul'\n",
"bldg = metadata[metadata['building_id'] == TARGET_BUILDING].iloc[0]\n",
"print('='*55)\n",
"print(f'BUILDING  : {bldg[\"building_id\"]}')\n",
"print(f'Site      : {bldg[\"site_id\"]}')\n",
"print(f'Usage     : {bldg[\"primaryspaceusage\"]} - {bldg[\"sub_primaryspaceusage\"]}')\n",
"print(f'Area      : {bldg[\"sqm\"]} m2  /  {bldg[\"sqft\"]} ft2')\n",
"print(f'Timezone  : {bldg[\"timezone\"]}')\n",
"print(f'Utilities : Electricity={bldg[\"electricity\"]}, HotWater={bldg[\"hotwater\"]}, Chilled={bldg[\"chilledwater\"]}')\n",
"print('='*55)\n",
"\n",
"print('\\nML Dataset Head:')\n",
"display(ml_dataset.head())\n",
"\n",
"print('\\nData Types & Missing Values:')\n",
"info = pd.DataFrame({\n",
"    'dtype': ml_dataset.dtypes,\n",
"    'non_null': ml_dataset.notnull().sum(),\n",
"    'missing': ml_dataset.isnull().sum()\n",
"})\n",
"display(info)\n",
),

# ─── SECTION 2: EDA ───────────────────────────────────────────────────────────
md("## 2. Exploratory Data Analysis\n"),
code(
"df = ml_dataset.copy()\n",
"print('Statistical Summary:')\n",
"display(df.describe().T.round(3))\n",
),
code(
"fig = plt.figure(figsize=(20, 16))\n",
"fig.suptitle('Eagle Education Paul - Electricity Demand EDA', fontsize=16, color=ACCENT, y=1.01)\n",
"gs  = gridspec.GridSpec(3, 3, figure=fig, hspace=0.45, wspace=0.35)\n",
"\n",
"ax1 = fig.add_subplot(gs[0, :])\n",
"ax1.plot(df['timestamp'], df['electricity'], color=ACCENT, linewidth=0.6, alpha=0.85)\n",
"ax1.fill_between(df['timestamp'], df['electricity'], alpha=0.15, color=ACCENT)\n",
"ax1.set_title('Hourly Electricity Demand Over Time')\n",
"ax1.set_ylabel('Electricity (kWh)'); ax1.grid(True)\n",
"\n",
"ax2 = fig.add_subplot(gs[1, 0])\n",
"ax2.hist(df['electricity'], bins=50, color=ACCENT, edgecolor='#0d1117', alpha=0.9)\n",
"ax2.axvline(df['electricity'].mean(), color=WARN, linestyle='--',\n",
"            label=f'Mean: {df[\"electricity\"].mean():.1f}')\n",
"ax2.set_title('Electricity Distribution')\n",
"ax2.set_xlabel('kWh'); ax2.set_ylabel('Frequency'); ax2.legend()\n",
"\n",
"ax3 = fig.add_subplot(gs[1, 1])\n",
"hourly_avg = df.groupby('hour')['electricity'].mean()\n",
"bars = ax3.bar(hourly_avg.index, hourly_avg.values, color=ACCENT, edgecolor='#0d1117')\n",
"bars[hourly_avg.idxmax()].set_color(WARN)\n",
"ax3.set_title('Avg Electricity by Hour')\n",
"ax3.set_xlabel('Hour'); ax3.grid(True, axis='y')\n",
"\n",
"ax4 = fig.add_subplot(gs[1, 2])\n",
"monthly_avg = df.groupby('month')['electricity'].mean()\n",
"months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']\n",
"ax4.bar([months[m-1] for m in monthly_avg.index], monthly_avg.values,\n",
"        color=ACCENT2, edgecolor='#0d1117')\n",
"ax4.set_title('Avg Electricity by Month')\n",
"ax4.tick_params(axis='x', rotation=45); ax4.grid(True, axis='y')\n",
"\n",
"ax5 = fig.add_subplot(gs[2, 0])\n",
"sc = ax5.scatter(df['airTemperature'], df['electricity'],\n",
"                 c=df['hour'], cmap='viridis', alpha=0.4, s=5)\n",
"plt.colorbar(sc, ax=ax5, label='Hour')\n",
"ax5.set_title('Air Temperature vs Electricity')\n",
"ax5.set_xlabel('Air Temp (C)'); ax5.set_ylabel('kWh')\n",
"\n",
"ax6 = fig.add_subplot(gs[2, 1])\n",
"df.groupby('is_weekend')['electricity'].mean().plot(\n",
"    kind='bar', ax=ax6, color=[ACCENT, WARN], edgecolor='#0d1117')\n",
"ax6.set_xticklabels(['Weekday','Weekend'], rotation=0)\n",
"ax6.set_title('Weekday vs Weekend Electricity')\n",
"ax6.set_ylabel('kWh'); ax6.grid(True, axis='y')\n",
"\n",
"ax7 = fig.add_subplot(gs[2, 2])\n",
"num_cols = ['electricity','airTemperature','dewTemperature','cloudCoverage',\n",
"            'seaLvlPressure','windSpeed','hour','month','electricity_lag_1']\n",
"corr = df[num_cols].corr()\n",
"sns.heatmap(corr, ax=ax7, cmap='coolwarm', annot=True, fmt='.2f',\n",
"            annot_kws={'size':7}, linewidths=0.5, linecolor='#0d1117')\n",
"ax7.set_title('Correlation Matrix')\n",
"ax7.tick_params(axis='x', rotation=45, labelsize=8)\n",
"ax7.tick_params(axis='y', rotation=0,  labelsize=8)\n",
"\n",
"plt.savefig('eda_plots.png', dpi=150, bbox_inches='tight', facecolor='#0d1117')\n",
"plt.show()\n",
"print('EDA plots saved to eda_plots.png')\n",
),

# ─── SECTION 3: FEATURE ENGINEERING ──────────────────────────────────────────
md("## 3. Feature Engineering\n"),
code(
"df = ml_dataset.copy().sort_values('timestamp').reset_index(drop=True)\n",
"\n",
"# --- Temporal ---\n",
"df['day_of_year']   = df['timestamp'].dt.dayofyear\n",
"df['quarter']       = df['timestamp'].dt.quarter\n",
"df['is_morning']    = ((df['hour'] >= 6)  & (df['hour'] < 12)).astype(int)\n",
"df['is_afternoon']  = ((df['hour'] >= 12) & (df['hour'] < 17)).astype(int)\n",
"df['is_evening']    = ((df['hour'] >= 17) & (df['hour'] < 21)).astype(int)\n",
"df['is_night']      = ((df['hour'] >= 21) | (df['hour'] <  6)).astype(int)\n",
"df['is_school_hrs'] = ((df['hour'] >= 8)  & (df['hour'] <= 17) & (df['is_weekend'] == 0)).astype(int)\n",
"\n",
"# --- Cyclical encodings ---\n",
"df['hour_sin']  = np.sin(2 * np.pi * df['hour']        / 24)\n",
"df['hour_cos']  = np.cos(2 * np.pi * df['hour']        / 24)\n",
"df['month_sin'] = np.sin(2 * np.pi * df['month']       / 12)\n",
"df['month_cos'] = np.cos(2 * np.pi * df['month']       / 12)\n",
"df['dow_sin']   = np.sin(2 * np.pi * df['day_of_week'] /  7)\n",
"df['dow_cos']   = np.cos(2 * np.pi * df['day_of_week'] /  7)\n",
"\n",
"# --- Weather-derived ---\n",
"df['temp_dew_diff'] = df['airTemperature'] - df['dewTemperature']\n",
"df['feels_like']    = df['airTemperature'] - 0.4*(df['airTemperature']-10)*(1-df['dewTemperature']/100)\n",
"df['wind_chill']    = df['airTemperature'] - df['windSpeed'] * 0.7\n",
"df['pressure_diff'] = df['seaLvlPressure'] - df['seaLvlPressure'].mean()\n",
"\n",
"# --- Rolling electricity ---\n",
"df['elec_roll_mean_3']  = df['electricity_lag_1'].rolling(3,  min_periods=1).mean().shift(1)\n",
"df['elec_roll_mean_6']  = df['electricity_lag_1'].rolling(6,  min_periods=1).mean().shift(1)\n",
"df['elec_roll_std_24']  = df['electricity_lag_1'].rolling(24, min_periods=1).std().shift(1).fillna(0)\n",
"df['elec_roll_max_24']  = df['electricity_lag_1'].rolling(24, min_periods=1).max().shift(1)\n",
"\n",
"# --- Building constant ---\n",
"df['sqm'] = 4008.1\n",
"\n",
"df = df.dropna().reset_index(drop=True)\n",
"\n",
"new_feats = ['day_of_year','quarter','is_morning','is_afternoon','is_evening','is_night',\n",
"             'is_school_hrs','hour_sin','hour_cos','month_sin','month_cos','dow_sin','dow_cos',\n",
"             'temp_dew_diff','feels_like','wind_chill','pressure_diff',\n",
"             'elec_roll_mean_3','elec_roll_mean_6','elec_roll_std_24','elec_roll_max_24','sqm']\n",
"print('='*55)\n",
"print('FEATURE ENGINEERING COMPLETE')\n",
"print('='*55)\n",
"print(f'  Total rows  : {len(df):,}')\n",
"print(f'  Total cols  : {df.shape[1]}')\n",
"print(f'  New features: {len(new_feats)}')\n",
"for f in new_feats:\n",
"    print(f'    + {f}')\n",
),

# ─── SECTION 4: SPLIT ─────────────────────────────────────────────────────────
md("## 4. Train / Test Split (Chronological)\n"),
code(
"FEATURE_COLS = [\n",
"    'airTemperature','dewTemperature','cloudCoverage','seaLvlPressure','windDirection','windSpeed',\n",
"    'hour','day_of_week','month','is_weekend',\n",
"    'electricity_lag_1','electricity_lag_24','electricity_lag_168',\n",
"    'day_of_year','quarter',\n",
"    'is_morning','is_afternoon','is_evening','is_night','is_school_hrs',\n",
"    'hour_sin','hour_cos','month_sin','month_cos','dow_sin','dow_cos',\n",
"    'temp_dew_diff','feels_like','wind_chill','pressure_diff',\n",
"    'elec_roll_mean_3','elec_roll_mean_6','elec_roll_std_24','elec_roll_max_24',\n",
"    'sqm',\n",
"]\n",
"TARGET_COL = 'electricity'\n",
"\n",
"X = df[FEATURE_COLS]\n",
"y = df[TARGET_COL]\n",
"\n",
"split_idx = int(len(df) * 0.80)\n",
"X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]\n",
"y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]\n",
"ts_test = df['timestamp'].iloc[split_idx:].reset_index(drop=True)\n",
"\n",
"print('='*55)\n",
"print('TRAIN / TEST SPLIT  (chronological - no leakage)')\n",
"print('='*55)\n",
"print(f'  Training samples : {len(X_train):,}  ({100*len(X_train)/len(df):.0f}%)')\n",
"print(f'  Testing  samples : {len(X_test):,}  ({100*len(X_test)/len(df):.0f}%)')\n",
"print(f'  Features used    : {len(FEATURE_COLS)}')\n",
"print(f'  Train period     : {df[\"timestamp\"].iloc[0]}  to  {df[\"timestamp\"].iloc[split_idx-1]}')\n",
"print(f'  Test  period     : {df[\"timestamp\"].iloc[split_idx]}  to  {df[\"timestamp\"].iloc[-1]}')\n",
),

# ─── SECTION 5: BASELINE ──────────────────────────────────────────────────────
md("## 5. Baseline Random Forest Model\n"),
code(
"print('Training Baseline Random Forest...')\n",
"rf_baseline = RandomForestRegressor(\n",
"    n_estimators=100, max_depth=None,\n",
"    min_samples_split=2, random_state=42, n_jobs=-1)\n",
"rf_baseline.fit(X_train, y_train)\n",
"y_pred_base = rf_baseline.predict(X_test)\n",
"\n",
"mae_base  = mean_absolute_error(y_test, y_pred_base)\n",
"rmse_base = np.sqrt(mean_squared_error(y_test, y_pred_base))\n",
"r2_base   = r2_score(y_test, y_pred_base)\n",
"\n",
"print()\n",
"print('='*40)\n",
"print('BASELINE MODEL PERFORMANCE')\n",
"print('='*40)\n",
"print(f'MAE  : {mae_base:.4f}')\n",
"print(f'RMSE : {rmse_base:.4f}')\n",
"print(f'R2   : {r2_base:.4f}')\n",
),

# ─── SECTION 6: TUNING ────────────────────────────────────────────────────────
md("## 6. Hyperparameter Tuning (RandomizedSearchCV)\n"),
code(
"param_dist = {\n",
"    'n_estimators'     : randint(100, 500),\n",
"    'max_depth'        : [None, 10, 20, 30, 40],\n",
"    'min_samples_split': randint(2, 15),\n",
"    'min_samples_leaf' : randint(1, 10),\n",
"    'max_features'     : ['sqrt', 'log2', 0.5, 0.8],\n",
"    'bootstrap'        : [True, False],\n",
"}\n",
"print('Running RandomizedSearchCV (may take a few minutes)...')\n",
"rf_search = RandomizedSearchCV(\n",
"    RandomForestRegressor(random_state=42, n_jobs=-1),\n",
"    param_distributions=param_dist,\n",
"    n_iter=30, cv=3,\n",
"    scoring='neg_mean_absolute_error',\n",
"    verbose=1, random_state=42, n_jobs=-1\n",
")\n",
"rf_search.fit(X_train, y_train)\n",
"print()\n",
"print('Best parameters found:')\n",
"for k, v in rf_search.best_params_.items():\n",
"    print(f'  {k:<25}: {v}')\n",
"print(f'  Best CV MAE : {-rf_search.best_score_:.4f}')\n",
),

# ─── SECTION 7: TUNED EVAL ────────────────────────────────────────────────────
md("## 7. Tuned Model Evaluation\n"),
code(
"rf_tuned    = rf_search.best_estimator_\n",
"y_pred_tune = rf_tuned.predict(X_test)\n",
"\n",
"mae_tune  = mean_absolute_error(y_test, y_pred_tune)\n",
"rmse_tune = np.sqrt(mean_squared_error(y_test, y_pred_tune))\n",
"r2_tune   = r2_score(y_test, y_pred_tune)\n",
"\n",
"print()\n",
"print('='*40)\n",
"print('TUNED MODEL PERFORMANCE:')\n",
"print('='*40)\n",
"print(f'MAE  : {mae_tune:.4f}')\n",
"print(f'RMSE : {rmse_tune:.4f}')\n",
"print(f'R2   : {r2_tune:.4f}')\n",
"print()\n",
"print('='*40)\n",
"print('MODEL COMPARISON')\n",
"print('='*40)\n",
"print(f'{\"Metric\":<8} {\"Baseline\":>10} {\"Tuned\":>10}')\n",
"print(f'{\"MAE\":<8} {mae_base:>10.4f} {mae_tune:>10.4f}')\n",
"print(f'{\"RMSE\":<8} {rmse_base:>10.4f} {rmse_tune:>10.4f}')\n",
"print(f'{\"R2\":<8} {r2_base:>10.4f} {r2_tune:>10.4f}')\n",
"print()\n",
"print('='*40)\n",
"print('IMPROVEMENT')\n",
"print('='*40)\n",
"mae_imp  = (mae_base  - mae_tune)  / mae_base  * 100\n",
"rmse_imp = (rmse_base - rmse_tune) / rmse_base * 100\n",
"r2_imp   = (r2_tune   - r2_base)   / abs(r2_base) * 100\n",
"print(f'MAE  improvement : {mae_imp:.2f}%')\n",
"print(f'RMSE improvement: {rmse_imp:.2f}%')\n",
"print(f'R2   improvement : {r2_imp:.2f}%')\n",
),

# ─── SECTION 8: FEATURE IMPORTANCE ───────────────────────────────────────────
md("## 8. Feature Importance\n"),
code(
"importances = pd.Series(rf_tuned.feature_importances_, index=FEATURE_COLS).sort_values(ascending=False)\n",
"print()\n",
"print('='*40)\n",
"print('FEATURE IMPORTANCE')\n",
"print('='*40)\n",
"print(f'  {\"feature\":<25} {\"importance\":>10}')\n",
"for feat, imp in importances.items():\n",
"    print(f'  {feat:<25} {imp:>10.6f}')\n",
"\n",
"fig, ax = plt.subplots(figsize=(12, 8))\n",
"top_n  = importances.head(20)\n",
"colors = [WARN if i < 3 else ACCENT for i in range(len(top_n))]\n",
"ax.barh(top_n.index[::-1], top_n.values[::-1], color=colors[::-1], edgecolor='#0d1117')\n",
"ax.set_title('Top 20 Feature Importances - Tuned Random Forest', fontsize=13, color=ACCENT)\n",
"ax.set_xlabel('Importance Score'); ax.grid(True, axis='x')\n",
"for bar, val in zip(ax.patches, top_n.values[::-1]):\n",
"    ax.text(bar.get_width()+0.001, bar.get_y()+bar.get_height()/2,\n",
"            f'{val:.4f}', va='center', ha='left', fontsize=8, color='#c9d1d9')\n",
"plt.tight_layout()\n",
"plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight', facecolor='#0d1117')\n",
"plt.show()\n",
"print('Feature importance saved to feature_importance.png')\n",
),

# ─── SECTION 9: PREDICTIONS PLOTS ────────────────────────────────────────────
md("## 9. Predictions vs Actual\n"),
code(
"fig, axes = plt.subplots(3, 1, figsize=(18, 14))\n",
"fig.suptitle('HVAC Electricity Forecast - Eagle Education Paul', fontsize=15, color=ACCENT)\n",
"\n",
"ax = axes[0]\n",
"ax.plot(ts_test.values, y_test.values,  color='#c9d1d9', linewidth=0.8, label='Actual', alpha=0.9)\n",
"ax.plot(ts_test.values, y_pred_tune,    color=ACCENT,    linewidth=0.8, label='Predicted', alpha=0.9)\n",
"ax.set_title('Full Test Period - Actual vs Predicted')\n",
"ax.set_ylabel('Electricity (kWh)'); ax.legend(); ax.grid(True)\n",
"\n",
"ax2 = axes[1]\n",
"n   = min(168, len(ts_test))\n",
"ax2.plot(ts_test.values[:n], y_test.values[:n], color='#c9d1d9', linewidth=1.2, label='Actual')\n",
"ax2.plot(ts_test.values[:n], y_pred_tune[:n],   color=WARN, linewidth=1.2, label='Predicted', linestyle='--')\n",
"ax2.fill_between(ts_test.values[:n],\n",
"                 y_pred_tune[:n]-mae_tune, y_pred_tune[:n]+mae_tune,\n",
"                 alpha=0.2, color=WARN, label=f'+/-MAE ({mae_tune:.2f} kWh)')\n",
"ax2.set_title('First 7 Days of Test Period (with +/-MAE band)')\n",
"ax2.set_ylabel('kWh'); ax2.legend(); ax2.grid(True)\n",
"\n",
"ax3 = axes[2]\n",
"residuals = y_test.values - y_pred_tune\n",
"ax3.plot(ts_test.values, residuals, color=ACCENT2, linewidth=0.6, alpha=0.8)\n",
"ax3.axhline(0, color=WARN, linestyle='--', linewidth=1)\n",
"ax3.fill_between(ts_test.values, residuals, 0, alpha=0.2, color=ACCENT2)\n",
"ax3.set_title('Prediction Residuals (Actual - Predicted)')\n",
"ax3.set_ylabel('Residual (kWh)'); ax3.set_xlabel('Timestamp'); ax3.grid(True)\n",
"\n",
"plt.tight_layout()\n",
"plt.savefig('predictions_vs_actual.png', dpi=150, bbox_inches='tight', facecolor='#0d1117')\n",
"plt.show()\n",
),
code(
"fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))\n",
"fig.suptitle('Model Fit Diagnostics', fontsize=13, color=ACCENT)\n",
"\n",
"ax1.scatter(y_test, y_pred_tune, alpha=0.3, s=8, color=ACCENT)\n",
"mn, mx = min(y_test.min(), y_pred_tune.min()), max(y_test.max(), y_pred_tune.max())\n",
"ax1.plot([mn, mx], [mn, mx], color=WARN, linewidth=1.5, label='Perfect fit')\n",
"ax1.set_title(f'Actual vs Predicted  (R2 = {r2_tune:.4f})')\n",
"ax1.set_xlabel('Actual (kWh)'); ax1.set_ylabel('Predicted (kWh)'); ax1.legend(); ax1.grid(True)\n",
"\n",
"ax2.hist(residuals, bins=60, color=ACCENT, edgecolor='#0d1117', alpha=0.9)\n",
"ax2.axvline(0, color=WARN, linestyle='--')\n",
"ax2.axvline(residuals.mean(), color=ACCENT2, linestyle='--',\n",
"            label=f'Mean={residuals.mean():.3f}')\n",
"ax2.set_title('Residual Distribution')\n",
"ax2.set_xlabel('Residual (kWh)'); ax2.legend(); ax2.grid(True)\n",
"\n",
"plt.tight_layout()\n",
"plt.savefig('model_diagnostics.png', dpi=150, bbox_inches='tight', facecolor='#0d1117')\n",
"plt.show()\n",
),

# ─── SECTION 10: HVAC LOGIC ───────────────────────────────────────────────────
md(
"## 10. HVAC Decision Logic\n",
"\n",
"The electricity forecast drives HVAC **setpoints** and **mode** commands sent to the ESP32.\n",
),
code(
"def hvac_command(predicted_kwh, air_temp, hour, is_weekend, occupancy=1):\n",
"    \"\"\"Convert ML electricity forecast + sensor readings into HVAC commands.\"\"\"\n",
"    school_hours = (8 <= hour <= 17) and not is_weekend\n",
"\n",
"    if not occupancy and not school_hours:\n",
"        return {'mode':'STANDBY','setpoint_cool':28.0,'setpoint_heat':15.0,\n",
"                'fan_speed':'OFF','demand_kWh':round(predicted_kwh,3),\n",
"                'status':'Unoccupied - HVAC in standby'}\n",
"\n",
"    if predicted_kwh > 60:\n",
"        if air_temp > 22:\n",
"            return {'mode':'COOL_SETBACK','setpoint_cool':26.0,'setpoint_heat':18.0,\n",
"                    'fan_speed':'LOW','demand_kWh':round(predicted_kwh,3),\n",
"                    'status':'High demand - cooling setback active'}\n",
"        else:\n",
"            return {'mode':'HEAT_SETBACK','setpoint_cool':24.0,'setpoint_heat':17.0,\n",
"                    'fan_speed':'LOW','demand_kWh':round(predicted_kwh,3),\n",
"                    'status':'High demand - heating setback active'}\n",
"\n",
"    if air_temp >= 26:\n",
"        return {'mode':'COOL','setpoint_cool':22.0,'setpoint_heat':18.0,\n",
"                'fan_speed':'HIGH' if air_temp > 30 else 'MEDIUM',\n",
"                'demand_kWh':round(predicted_kwh,3),'status':'Cooling mode - occupied comfort'}\n",
"\n",
"    if air_temp <= 18:\n",
"        return {'mode':'HEAT','setpoint_cool':24.0,'setpoint_heat':21.0,\n",
"                'fan_speed':'MEDIUM','demand_kWh':round(predicted_kwh,3),\n",
"                'status':'Heating mode - occupied comfort'}\n",
"\n",
"    return {'mode':'VENTILATE','setpoint_cool':24.0,'setpoint_heat':20.0,\n",
"            'fan_speed':'LOW','demand_kWh':round(predicted_kwh,3),\n",
"            'status':'Comfortable - ventilation only'}\n",
"\n",
"\n",
"test_df = df.iloc[split_idx:].reset_index(drop=True)\n",
"test_df['predicted_electricity'] = y_pred_tune\n",
"\n",
"hvac_results = test_df.apply(\n",
"    lambda row: hvac_command(\n",
"        row['predicted_electricity'], row['airTemperature'],\n",
"        int(row['hour']), int(row['is_weekend']), occupancy=1), axis=1\n",
").apply(pd.Series)\n",
"\n",
"test_df = pd.concat([\n",
"    test_df[['timestamp','electricity','predicted_electricity','airTemperature','hour','is_weekend']],\n",
"    hvac_results\n",
"], axis=1)\n",
"\n",
"print('='*60)\n",
"print('SAMPLE HVAC COMMANDS (first 10 test hours)')\n",
"print('='*60)\n",
"print(test_df[['timestamp','airTemperature','hour','electricity',\n",
"               'predicted_electricity','mode','setpoint_cool',\n",
"               'setpoint_heat','fan_speed']].head(10).to_string())\n",
"print()\n",
"print('HVAC Mode Distribution:')\n",
"print(test_df['mode'].value_counts().to_string())\n",
),
code(
"fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(16, 10))\n",
"fig.suptitle('HVAC Mode Analysis - Eagle Education Paul', fontsize=14, color=ACCENT)\n",
"\n",
"mode_colors = {'COOL':'#58a6ff','HEAT':'#f78166','VENTILATE':'#3fb950',\n",
"               'STANDBY':'#8b949e','COOL_SETBACK':'#d2a8ff','HEAT_SETBACK':'#ffa657'}\n",
"\n",
"counts = test_df['mode'].value_counts()\n",
"ax1.bar(counts.index, counts.values,\n",
"        color=[mode_colors.get(m, ACCENT) for m in counts.index], edgecolor='#0d1117')\n",
"ax1.set_title('HVAC Mode Distribution Over Test Period')\n",
"ax1.set_ylabel('Hours'); ax1.grid(True, axis='y')\n",
"for i, (m, v) in enumerate(counts.items()):\n",
"    ax1.text(i, v+1, str(v), ha='center', fontsize=9, color='#c9d1d9')\n",
"\n",
"sample   = test_df.iloc[:168]\n",
"mode_map = {m: i for i, m in enumerate(mode_colors.keys())}\n",
"ax2.scatter(sample['timestamp'], sample['mode'].map(mode_map),\n",
"            c=[mode_colors.get(m, ACCENT) for m in sample['mode']], s=15, alpha=0.8)\n",
"ax2.set_yticks(list(mode_map.values()))\n",
"ax2.set_yticklabels(list(mode_map.keys()))\n",
"ax2.set_title('HVAC Mode Timeline - First 7 Days of Test')\n",
"ax2.set_xlabel('Timestamp'); ax2.grid(True)\n",
"\n",
"plt.tight_layout()\n",
"plt.savefig('hvac_mode_analysis.png', dpi=150, bbox_inches='tight', facecolor='#0d1117')\n",
"plt.show()\n",
),

# ─── SECTION 11: SAVE MODEL ───────────────────────────────────────────────────
md("## 11. Save Model & Test Predictions\n"),
code(
"MODEL_PATH = 'random_forest_energy_model.pkl'\n",
"joblib.dump(rf_tuned, MODEL_PATH)\n",
"print('='*40)\n",
"print('MODEL SAVED')\n",
"print('='*40)\n",
"print(f'{MODEL_PATH}')\n",
"\n",
"CSV_PATH = 'test_predictions.csv'\n",
"test_df.to_csv(CSV_PATH, index=False)\n",
"print(f'{CSV_PATH} saved successfully!')\n",
"\n",
"with open('model_features.json', 'w') as f:\n",
"    json.dump({\n",
"        'features': FEATURE_COLS, 'target': TARGET_COL,\n",
"        'mae': round(mae_tune,4), 'rmse': round(rmse_tune,4), 'r2': round(r2_tune,4)\n",
"    }, f, indent=2)\n",
"print('model_features.json saved!')\n",
),

# ─── SECTION 12: FINAL INTERPRETATION ────────────────────────────────────────
md("## 12. Final Interpretation\n"),
code(
"print()\n",
"print('='*40)\n",
"print('FINAL INTERPRETATION')\n",
"print('='*40)\n",
"print()\n",
"print(f'The tuned Random Forest explains approximately {r2_tune*100:.2f}% of the variation in building electricity demand.')\n",
"print()\n",
"print(f'Average absolute prediction error (MAE): {mae_tune:.4f}')\n",
"print()\n",
"print(f'RMSE: {rmse_tune:.4f}')\n",
"print()\n",
"if rmse_tune > mae_tune:\n",
"    print('RMSE is higher than MAE, indicating that some larger prediction errors are present.')\n",
"print()\n",
"print('Top 3 most important features:')\n",
"for rank, (feat, imp) in enumerate(list(importances.head(3).items()), 1):\n",
"    print(f'  {rank}. {feat} ({imp:.6f})')\n",
"print()\n",
"print('HVAC Integration:')\n",
"print('  Predictions feed directly into hvac_command() function.')\n",
"print('  ESP32 reads sensor data -> sends to Python API -> receives HVAC mode + setpoints.')\n",
"print()\n",
"print('='*40)\n",
"print('ML MODEL TRAINING COMPLETED')\n",
"print('='*40)\n",
),

# ─── SECTION 13: ESP32 CODE ───────────────────────────────────────────────────
md(
"---\n",
"## 13. ESP32 Arduino Code\n",
"\n",
"| Sensor | Pin | Measures |\n",
"|---|---|---|\n",
"| DHT22 | GPIO 4 | Temperature, Humidity |\n",
"| BMP280 | I2C (21/22) | Barometric Pressure |\n",
"| MQ-135 | GPIO 34 (ADC) | Air Quality / CO2 |\n",
"| PIR HC-SR501 | GPIO 5 | Occupancy |\n",
"| Relay Module | GPIO 26/27/25 | HVAC ON/OFF control |\n",
),
code(
"arduino_sketch = '''\n",
"// ============================================================\n",
"// ESP32 HVAC Controller - Eagle Education Paul\n",
"// Sensors: DHT22, BMP280, MQ-135, PIR HC-SR501\n",
"// POST sensor JSON to Python ML API, receive HVAC mode\n",
"// ============================================================\n",
"#include <WiFi.h>\n",
"#include <HTTPClient.h>\n",
"#include <ArduinoJson.h>\n",
"#include <DHT.h>\n",
"#include <Wire.h>\n",
"#include <Adafruit_BMP280.h>\n",
"\n",
"#define DHT_PIN     4\n",
"#define DHT_TYPE    DHT22\n",
"#define MQ135_PIN   34\n",
"#define PIR_PIN     5\n",
"#define RELAY_COOL  26\n",
"#define RELAY_HEAT  27\n",
"#define RELAY_FAN   25\n",
"\n",
"const char* SSID     = \"YOUR_WIFI_SSID\";\n",
"const char* PASSWORD = \"YOUR_WIFI_PASSWORD\";\n",
"const char* API_URL  = \"http://192.168.1.100:8000/predict\";\n",
"\n",
"DHT dht(DHT_PIN, DHT_TYPE);\n",
"Adafruit_BMP280 bmp;\n",
"String current_mode = \"STANDBY\";\n",
"\n",
"void setup() {\n",
"  Serial.begin(115200);\n",
"  dht.begin();\n",
"  Wire.begin(21, 22);\n",
"  bmp.begin(0x76);\n",
"  pinMode(PIR_PIN, INPUT);\n",
"  pinMode(RELAY_COOL, OUTPUT);\n",
"  pinMode(RELAY_HEAT, OUTPUT);\n",
"  pinMode(RELAY_FAN,  OUTPUT);\n",
"  digitalWrite(RELAY_COOL, HIGH);\n",
"  digitalWrite(RELAY_HEAT, HIGH);\n",
"  digitalWrite(RELAY_FAN,  HIGH);\n",
"  WiFi.begin(SSID, PASSWORD);\n",
"  Serial.print(\"Connecting\");\n",
"  while (WiFi.status() != WL_CONNECTED) { delay(500); Serial.print(\".\"); }\n",
"  Serial.println(\"Connected: \" + WiFi.localIP().toString());\n",
"}\n",
"\n",
"struct SensorData { float temp, hum, pres; int aq, occ; };\n",
"\n",
"SensorData readSensors() {\n",
"  SensorData s;\n",
"  s.temp = dht.readTemperature();\n",
"  s.hum  = dht.readHumidity();\n",
"  s.pres = bmp.readPressure() / 100.0F;\n",
"  s.aq   = analogRead(MQ135_PIN);\n",
"  s.occ  = digitalRead(PIR_PIN);\n",
"  if (isnan(s.temp)) s.temp = 22.0;\n",
"  if (isnan(s.hum))  s.hum  = 50.0;\n",
"  return s;\n",
"}\n",
"\n",
"int getCurrentHour() { return (millis() / 3600000UL) % 24; }\n",
"\n",
"String queryMLAPI(SensorData& s) {\n",
"  if (WiFi.status() != WL_CONNECTED) return \"STANDBY\";\n",
"  HTTPClient http;\n",
"  http.begin(API_URL);\n",
"  http.addHeader(\"Content-Type\", \"application/json\");\n",
"  StaticJsonDocument<256> doc;\n",
"  doc[\"air_temperature\"] = s.temp;\n",
"  doc[\"humidity\"]        = s.hum;\n",
"  doc[\"pressure\"]        = s.pres;\n",
"  doc[\"air_quality\"]     = s.aq;\n",
"  doc[\"occupancy\"]       = s.occ;\n",
"  doc[\"hour\"]            = getCurrentHour();\n",
"  doc[\"building\"]        = \"Eagle_education_Paul\";\n",
"  String body; serializeJson(doc, body);\n",
"  int code = http.POST(body);\n",
"  String mode = \"STANDBY\";\n",
"  if (code == HTTP_CODE_OK) {\n",
"    StaticJsonDocument<512> resp;\n",
"    deserializeJson(resp, http.getString());\n",
"    mode = resp[\"mode\"].as<String>();\n",
"    Serial.printf(\"[API] Mode:%s Cool:%.1f Heat:%.1f kWh:%.2f\\n\",\n",
"      mode.c_str(),(float)resp[\"setpoint_cool\"],(float)resp[\"setpoint_heat\"],(float)resp[\"demand_kWh\"]);\n",
"  } else { Serial.printf(\"[API] Error: %d\\n\", code); }\n",
"  http.end(); return mode;\n",
"}\n",
"\n",
"void applyHVAC(String mode) {\n",
"  if (mode==\"COOL\"||mode==\"COOL_SETBACK\"){\n",
"    digitalWrite(RELAY_COOL,LOW); digitalWrite(RELAY_HEAT,HIGH); digitalWrite(RELAY_FAN,LOW);\n",
"  } else if (mode==\"HEAT\"||mode==\"HEAT_SETBACK\"){\n",
"    digitalWrite(RELAY_COOL,HIGH); digitalWrite(RELAY_HEAT,LOW); digitalWrite(RELAY_FAN,LOW);\n",
"  } else if (mode==\"VENTILATE\"){\n",
"    digitalWrite(RELAY_COOL,HIGH); digitalWrite(RELAY_HEAT,HIGH); digitalWrite(RELAY_FAN,LOW);\n",
"  } else {\n",
"    digitalWrite(RELAY_COOL,HIGH); digitalWrite(RELAY_HEAT,HIGH); digitalWrite(RELAY_FAN,HIGH);\n",
"  }\n",
"}\n",
"\n",
"void loop() {\n",
"  SensorData s = readSensors();\n",
"  Serial.printf(\"[Sensors] T:%.1f H:%.1f P:%.1f AQ:%d Occ:%d\\n\",s.temp,s.hum,s.pres,s.aq,s.occ);\n",
"  String mode = queryMLAPI(s);\n",
"  applyHVAC(mode);\n",
"  Serial.printf(\"[HVAC] Mode: %s\\n\\n\", mode.c_str());\n",
"  delay(60000);\n",
"}\n",
"'''\n",
"\n",
"with open('esp32_hvac_controller.ino', 'w') as f:\n",
"    f.write(arduino_sketch)\n",
"print('ESP32 Arduino sketch saved to esp32_hvac_controller.ino')\n",
"print('Required libraries: WiFi, HTTPClient, ArduinoJson, DHT, Adafruit_BMP280')\n",
),

# ─── SECTION 14: FASTAPI ──────────────────────────────────────────────────────
md("## 14. Python FastAPI Server (ESP32 <-> ML Bridge)\n"),
code(
"api_code = '''\n",
"from fastapi import FastAPI\n",
"from pydantic import BaseModel\n",
"import joblib, json, numpy as np\n",
"from datetime import datetime\n",
"\n",
"app   = FastAPI(title=\"HVAC ML API - Eagle Education Paul\")\n",
"model = joblib.load(\"random_forest_energy_model.pkl\")\n",
"feats = json.load(open(\"model_features.json\"))[\"features\"]\n",
"\n",
"class Payload(BaseModel):\n",
"    air_temperature: float; humidity: float; pressure: float\n",
"    air_quality: int; occupancy: int; hour: int\n",
"    building: str = \"Eagle_education_Paul\"\n",
"\n",
"def hvac_cmd(kwh, temp, hour, wknd, occ):\n",
"    sch = (8<=hour<=17) and not wknd\n",
"    if not occ and not sch:\n",
"        return {\"mode\":\"STANDBY\",\"setpoint_cool\":28.0,\"setpoint_heat\":15.0,\"fan_speed\":\"OFF\",\"demand_kWh\":round(kwh,3)}\n",
"    if kwh>60:\n",
"        m=\"COOL_SETBACK\" if temp>22 else \"HEAT_SETBACK\"\n",
"        return {\"mode\":m,\"setpoint_cool\":26.0,\"setpoint_heat\":17.0,\"fan_speed\":\"LOW\",\"demand_kWh\":round(kwh,3)}\n",
"    if temp>=26:\n",
"        return {\"mode\":\"COOL\",\"setpoint_cool\":22.0,\"setpoint_heat\":18.0,\n",
"                \"fan_speed\":\"HIGH\" if temp>30 else \"MEDIUM\",\"demand_kWh\":round(kwh,3)}\n",
"    if temp<=18:\n",
"        return {\"mode\":\"HEAT\",\"setpoint_cool\":24.0,\"setpoint_heat\":21.0,\"fan_speed\":\"MEDIUM\",\"demand_kWh\":round(kwh,3)}\n",
"    return {\"mode\":\"VENTILATE\",\"setpoint_cool\":24.0,\"setpoint_heat\":20.0,\"fan_speed\":\"LOW\",\"demand_kWh\":round(kwh,3)}\n",
"\n",
"@app.get(\"/\") \n",
"def root(): return {\"status\":\"running\",\"building\":\"Eagle_education_Paul\"}\n",
"\n",
"@app.post(\"/predict\")\n",
"def predict(p: Payload):\n",
"    now=datetime.now(); wknd=int(now.weekday()>=5)\n",
"    dew=p.air_temperature-(100-p.humidity)/5\n",
"    fmap={\"airTemperature\":p.air_temperature,\"dewTemperature\":dew,\n",
"          \"cloudCoverage\":0.0,\"seaLvlPressure\":p.pressure,\n",
"          \"windDirection\":0.0,\"windSpeed\":0.0,\n",
"          \"hour\":float(p.hour),\"day_of_week\":float(now.weekday()),\n",
"          \"month\":float(now.month),\"is_weekend\":float(wknd),\"sqm\":4008.1}\n",
"    vec=np.array([fmap.get(f,0.0) for f in feats]).reshape(1,-1)\n",
"    kwh=float(model.predict(vec)[0])\n",
"    return hvac_cmd(kwh,p.air_temperature,p.hour,wknd,p.occupancy)\n",
"'''\n",
"\n",
"with open('hvac_api.py', 'w') as f:\n",
"    f.write(api_code)\n",
"print('FastAPI server saved to hvac_api.py')\n",
"print()\n",
"print('Start server:  uvicorn hvac_api:app --host 0.0.0.0 --port 8000')\n",
"print('ESP32 POSTs to: http://<your-pc-ip>:8000/predict')\n",
),

# ─── ARCHITECTURE ─────────────────────────────────────────────────────────────
md(
"---\n",
"## System Architecture\n",
"\n",
"```\n",
"Eagle Education Paul (Classroom 4008 m2)\n",
"          |\n",
"    [ESP32 Node]\n",
"     DHT22  GPIO4  -> Temperature + Humidity\n",
"     BMP280 I2C    -> Barometric Pressure\n",
"     MQ-135 GPIO34 -> CO2 / Air Quality\n",
"     PIR    GPIO5  -> Occupancy\n",
"          | HTTP POST (WiFi)\n",
"    [FastAPI Server - PC/RPi on LAN]\n",
"     random_forest_energy_model.pkl\n",
"     hvac_command() HVAC logic\n",
"          | JSON: mode + setpoints\n",
"    [ESP32 Relay Control]\n",
"     GPIO26 -> Cooling relay\n",
"     GPIO27 -> Heating relay\n",
"     GPIO25 -> Fan relay\n",
"```\n",
"\n",
"### HVAC Mode Reference\n",
"\n",
"| Mode | Condition | Cool SP | Heat SP | Fan |\n",
"|---|---|---|---|---|\n",
"| COOL | Temp >= 26C, occupied | 22C | 18C | MED/HIGH |\n",
"| HEAT | Temp <= 18C, occupied | 24C | 21C | MEDIUM |\n",
"| VENTILATE | 18C < Temp < 26C | 24C | 20C | LOW |\n",
"| COOL_SETBACK | Demand > 60 kWh, hot | 26C | 18C | LOW |\n",
"| HEAT_SETBACK | Demand > 60 kWh, cold | 24C | 17C | LOW |\n",
"| STANDBY | Unoccupied off-hours | 28C | 15C | OFF |\n",
"\n",
"---\n",
"*Eagle_education_Paul HVAC ML Forecasting System*\n",
),

]

nb = {
    'cells': cells,
    'metadata': {
        'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
        'language_info': {'name': 'python', 'version': '3.10.0'}
    },
    'nbformat': 4,
    'nbformat_minor': 5
}

with open(OUT, 'w', encoding='utf-8') as fh:
    json.dump(nb, fh, indent=1, ensure_ascii=False)

size = os.path.getsize(OUT)
print(f'Notebook written: {OUT}')
print(f'File size: {size:,} bytes ({size//1024} KB)')
print(f'Cells: {len(cells)}')

